using System.Security.Cryptography;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace RssReader.Api;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(IServiceProvider services)
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        await db.Database.EnsureCreatedAsync();
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"ImageUrl\" text;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"ImageBase64\" text;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"ImageMimeType\" text;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"Category\" text;");
        await db.Database.ExecuteSqlRawAsync("DROP INDEX IF EXISTS \"IX_Articles_UrlHash\";");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"IsFavorite\" boolean NOT NULL DEFAULT false;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"IsHidden\" boolean NOT NULL DEFAULT false;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"IsRead\" boolean NOT NULL DEFAULT false;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"IsDeleted\" boolean NOT NULL DEFAULT false;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"UrlHash\" text;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Articles\" ADD COLUMN IF NOT EXISTS \"TitleHash\" text;");
        var articlesWithoutIdentity = await db.Articles
            .Where(article => article.UrlHash == null || article.TitleHash == null)
            .Select(article => new { article.Id, article.Url, article.Title })
            .ToListAsync();
        foreach (var article in articlesWithoutIdentity)
        {
            var normalizedUrl = NormalizeArticleUrl(article.Url);
            var urlHash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(normalizedUrl)));
            var titleHash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(article.Title.Trim())));
            await db.Database.ExecuteSqlInterpolatedAsync($"UPDATE \"Articles\" SET \"UrlHash\" = {urlHash}, \"TitleHash\" = {titleHash} WHERE \"Id\" = {article.Id};");
        }
        await db.Database.ExecuteSqlRawAsync("DELETE FROM \"Articles\" older USING \"Articles\" newer WHERE older.\"Id\" > newer.\"Id\" AND older.\"UrlHash\" = newer.\"UrlHash\";");
        await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Articles_UrlHash\" ON \"Articles\" (\"UrlHash\") WHERE \"UrlHash\" IS NOT NULL;");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_Articles_TitleHash\" ON \"Articles\" (\"TitleHash\");");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Feeds\" ADD COLUMN IF NOT EXISTS \"LastCheckedAt\" timestamptz;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Feeds\" ADD COLUMN IF NOT EXISTS \"NextScheduledAt\" timestamptz;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Feeds\" ADD COLUMN IF NOT EXISTS \"LastError\" text;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Feeds\" ADD COLUMN IF NOT EXISTS \"LastCollectedCount\" integer NOT NULL DEFAULT 0;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Feeds\" ADD COLUMN IF NOT EXISTS \"Description\" text;");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Feeds\" ADD COLUMN IF NOT EXISTS \"PollIntervalMinutes\" integer NOT NULL DEFAULT 0;");
        await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS \"IngestionRuns\" (\"Id\" uuid PRIMARY KEY, \"FeedId\" uuid NOT NULL, \"StartedAt\" timestamptz NOT NULL, \"CompletedAt\" timestamptz NULL, \"Status\" text NOT NULL, \"ItemCount\" integer NOT NULL DEFAULT 0, \"PersistedCount\" integer NOT NULL DEFAULT 0, \"ErrorCount\" integer NOT NULL DEFAULT 0, \"Error\" text NULL);");
        await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"IngestionRuns\" ADD COLUMN IF NOT EXISTS \"ProcessedCount\" integer NOT NULL DEFAULT 0;");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_IngestionRuns_FeedId_StartedAt\" ON \"IngestionRuns\" (\"FeedId\", \"StartedAt\");");
        await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS \"IngestionErrors\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"RunId\" uuid NOT NULL, \"FeedId\" uuid NOT NULL, \"CreatedAt\" timestamptz NOT NULL, \"Stage\" text NOT NULL, \"ArticleUrl\" text NULL, \"Message\" text NOT NULL);");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_IngestionErrors_FeedId_CreatedAt\" ON \"IngestionErrors\" (\"FeedId\", \"CreatedAt\");");
    }

    private static string NormalizeArticleUrl(string url)
    {
        if (!Uri.TryCreate(url.Trim(), UriKind.Absolute, out var uri))
            return url.Trim();
        var builder = new UriBuilder(uri) { Fragment = string.Empty };
        return builder.Uri.ToString().TrimEnd('/');
    }
}
